[package]
name = "flux-screensaver-windows"
version = "1.1.0"
description = "An open-source tribute to the macOS Drift screensaver"
authors = ["Sander Melnikov <hey@sandydoo.me"]
repository = "https://github.com/sandydoo/flux-screensavers/"
edition = "2021"
build = "build.rs"

[package.metadata.winres]
ProductName = "Flux"
FileDescription = "An ode to the macOS Drift screensaver"
LegalCopyright = "Â© 2022 Sander Melnikov"

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
env_logger = "0.9"
glow = "0.11.2"
log = "0.4"
raw-window-handle = "0.4"
sdl2-sys = "0.35.2"

[dependencies.flux]
version = "4"
git = "https://github.com/sandydoo/flux"
tag = "v4.3.0"

[target.'cfg(not(windows))'.dependencies.sdl2]
version = "0.35.2"
default-features = false
features = [ "use-pkgconfig", "raw-window-handle" ]

[target.'cfg(windows)'.dependencies.sdl2]
version = "0.35.2"
default-features = false
features = [ "static-link", "raw-window-handle" ]

[target.'cfg(windows)'.dependencies.winapi]
version =  "0.3"
features = [ "winuser", "winerror", "shellscalingapi" ]

[build-dependencies]
winres = "0.1.12"

[patch.crates-io]
winres = { git = "https://github.com/sandydoo/winres", branch = "bugfix/fix-linking" }

# [patch."https://github.com/sandydoo/flux"]
# flux = { version = "4", path = "../../flux/flux" }
